export const projectsData = [
  {
    id: 1,
    title: "Projeto 1",
    description: "Descrição breve do Projeto 1.",
    detailedDescription: "Descrição detalhada do Projeto 1.",
    technologies: ["React", "JavaScript", "CSS3"],
    imageUrl: "https://placehold.co/600x400",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    projectUrl: "https://example.com/projeto1",
    githubUrl: "https://github.com/usuario/projeto1",
  },
  {
    id: 2,
    title: "Projeto 2",
    description: "Descrição breve do Projeto 2.",
    detailedDescription: "Descrição detalhada do Projeto 2.",
    technologies: ["HTML5", "SCSS", "NodeJS"],
    imageUrl: "https://placehold.co/600x400",
    videoUrl: "https://www.youtube.com/embed/3JZ_D3ELwOQ",
    projectUrl: "https://example.com/projeto2",
    githubUrl: "https://github.com/usuario/projeto2",
  },
    {
    id: 3,
    title: "Projeto 1",
    description: "Descrição breve do Projeto 1.",
    detailedDescription: "Descrição detalhada do Projeto 1.",
    technologies: ["React", "JavaScript", "CSS3"],
    imageUrl: "https://placehold.co/600x400",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    projectUrl: "https://example.com/projeto1",
    githubUrl: "https://github.com/usuario/projeto1",
  },
  {
    id: 4,
    title: "Projeto 2",
    description: "Descrição breve do Projeto 2.",
    detailedDescription: "Descrição detalhada do Projeto 2.",
    technologies: ["HTML5", "SCSS", "NodeJS"],
    imageUrl: "https://placehold.co/600x400",
    videoUrl: "https://www.youtube.com/embed/3JZ_D3ELwOQ",
    projectUrl: "https://example.com/projeto2",
    githubUrl: "https://github.com/usuario/projeto2",
  },
    {
    id: 5,
    title: "Projeto 1",
    description: "Descrição breve do Projeto 1.",
    detailedDescription: "Descrição detalhada do Projeto 1.",
    technologies: ["React", "JavaScript", "CSS3"],
    imageUrl: "https://placehold.co/600x400",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    projectUrl: "https://example.com/projeto1",
    githubUrl: "https://github.com/usuario/projeto1",
  },
  {
    id: 6,
    title: "Projeto 2",
    description: "Descrição breve do Projeto 2.",
    detailedDescription: "Descrição detalhada do Projeto 2.",
    technologies: ["HTML5", "SCSS", "NodeJS"],
    imageUrl: "https://placehold.co/600x400",
    videoUrl: "https://www.youtube.com/embed/3JZ_D3ELwOQ",
    projectUrl: "https://example.com/projeto2",
    githubUrl: "https://github.com/usuario/projeto2",
  },
    {
    id: 7,
    title: "Projeto 1",
    description: "Descrição breve do Projeto 1.",
    detailedDescription: "Descrição detalhada do Projeto 1.",
    technologies: ["React", "JavaScript", "CSS3"],
    imageUrl: "https://placehold.co/600x400",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    projectUrl: "https://example.com/projeto1",
    githubUrl: "https://github.com/usuario/projeto1",
  },
  {
    id: 8,
    title: "Projeto 2",
    description: "Descrição breve do Projeto 2.",
    detailedDescription: "Descrição detalhada do Projeto 2.",
    technologies: ["HTML5", "SCSS", "NodeJS"],
    imageUrl: "https://placehold.co/600x400",
    videoUrl: "https://www.youtube.com/embed/3JZ_D3ELwOQ",
    projectUrl: "https://example.com/projeto2",
    githubUrl: "https://github.com/usuario/projeto2",
  },
      {
    id: 9,
    title: "Projeto 1",
    description: "Descrição breve do Projeto 1.",
    detailedDescription: "Descrição detalhada do Projeto 1.",
    technologies: ["React", "JavaScript", "CSS3"],
    imageUrl: "https://placehold.co/600x400",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    projectUrl: "https://example.com/projeto1",
    githubUrl: "https://github.com/usuario/projeto1",
  },
  {
    id: 10,
    title: "Projeto 2",
    description: "Descrição breve do Projeto 2.",
    detailedDescription: "Descrição detalhada do Projeto 2.",
    technologies: ["HTML5", "SCSS", "NodeJS"],
    imageUrl: "https://placehold.co/600x400",
    videoUrl: "https://www.youtube.com/embed/3JZ_D3ELwOQ",
    projectUrl: "https://example.com/projeto2",
    githubUrl: "https://github.com/usuario/projeto2",
  },
];